---
output: github_document
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "img/README-pointbin-",
  out.width = "100%"
)
```

# Geom `geom_pointbin`

The geom `geom_pointdensity` from 
the [ggpointdensity](https://github.com/variani/ggpointdensity) package
implements two methods for 2D density estimation, 
nearest neighbors (`method="default"`) and 
`kde2d` (`method="kde2d"`) from the MASS package.

```{r inc}
library(ggpointdensity)

library(ggplot2)
library(dplyr)
library(viridis)

library(cowplot)
theme_set(theme_cowplot(12))
```

```{r sim_data}
N = 1e3
dat = bind_rows(
  tibble(x = rnorm(N, sd = 1), y = rnorm(N, sd = 10), group = "foo"),
  tibble(x = rnorm(N, mean = 1, sd = .5), y = rnorm(N, mean = 7, sd = 5), group = "bar"))
```

```{r plot_pointdensity_vs_pointbin}
p_base = ggplot(data = dat, mapping = aes(x = x, y = y))

p_nn = p_base + 
  geom_pointdensity(method = "default") +
  scale_color_viridis()

p_kde = p_base + 
  geom_pointdensity(method = "kde2d") +
  scale_color_viridis()

p_bin = p_base + 
  geom_pointbin() +
  scale_color_viridis()

plot_grid(
  p_nn + labs(subtitle = 'geom_pointdensity(method = "default")'),
  p_kde + labs(subtitle = 'geom_pointdensity(method = "kde2d"'),
  p_bin + labs(subtitle = 'geom_pointbin()'))
```



